version: '3.1'

services:

  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: SimpleDocument
      MONGO_INITDB_ROOT_PASSWORD: SimpleDocument

  backend:
    build: ./SimpleDocument-backend
    restart: unless-stopped
    environment:
      MONGO_URL: mongodb://SimpleDocument:SimpleDocument@mongo:27017
    ports:
      - 8080:3000